# Generated by Django 5.0.6 on 2024-07-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_project_issue_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
