# Generated by Django 5.0.6 on 2024-07-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_remove_issue_type_issue_types_alter_issue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproductionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproduction_steps', to='issues.issue')),
            ],
        ),
    ]
